apiVersion: v1
kind: Service
metadata:
  name: firewall-content-lbservice
  namespace: firewall
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: firewall-content